//! Re-exports [`TagName`] for backward compatibility.
//!
//! The canonical definition is now generated by the `define_tags!` macro in
//! the parent module.  This file exists so that `use crate::tag_defs::names::TagName`
//! continues to resolve.

pub use super::TagName;
